// <auto-generated />
using System;
using LerningApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LerningApp.Data.Migrations
{
    [DbContext(typeof(LerningAppContext))]
    [Migration("20260312170125_MakingTeacherTheCreatorOfAListeningQestion")]
    partial class MakingTeacherTheCreatorOfAListeningQestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LerningApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NativeLanguage")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LerningApp.Data.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK Unique Identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("The Creation Date of the Course");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("The Description of the Course");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the Course is deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasComment("The status of the Course");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The Name of the Course");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The Price of the Course");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Publisher of the Course");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK Unique Identifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("The Content of the Lesson");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Course");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("The Creation Date of the Lesson");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("The status of the Lesson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The Name of the Lesson");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasComment("The OrderIndex of the Lesson");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Publisher of the Lesson");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The Target of the Lesson");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK Unique Identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("The Description of the Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("The Name of the Level");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The Audio path of the exercise");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("The difficulty level of the exercise");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the exercise is deleted");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Lesson");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to ApplicationUser");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PublisherId");

                    b.ToTable("ListeningExercises");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningExerciseOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The answer of the exercise");

                    b.Property<Guid>("ListeningQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the Listening Question");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasComment("Order index of the answer");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("bit")
                        .HasComment("Whether the answer is correct or not");

                    b.HasKey("Id");

                    b.HasIndex("ListeningQuestionId");

                    b.HasIndex("ListeningQuestionId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ListeningExerciseOptions");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListeningExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningExerciseId");

                    b.HasIndex("PublisherId");

                    b.ToTable("ListeningQuestions");
                });

            modelBuilder.Entity("LerningApp.Data.Models.MultipleChoiceExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The Correct answer of the exercise");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("The difficulty level of the exercise");

                    b.Property<string>("FirstWrongAnswer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The First wrong answer of the exercise");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Lesson");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to ApplicationUser");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("The Question for the exercise");

                    b.Property<string>("SecondWrongAnswer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The Second wrong answer of the exercise");

                    b.Property<string>("ThirdWrongAnswer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The Third wrong answer of the exercise if needed");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PublisherId");

                    b.ToTable("MultipleChoiceExercises");
                });

            modelBuilder.Entity("LerningApp.Data.Models.PartOfSpeech", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK Unique Identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("The Name of the PartOfSpeech");

                    b.HasKey("Id");

                    b.ToTable("PartsOfSpeech");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("LerningApp.Data.Models.TranslationExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BulgarianSentence")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("The bulgarian sentence");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("The difficulty level of the exercise");

                    b.Property<string>("EnglishSentence")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("The english sentence");

                    b.Property<string>("GermanSentence")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("The german sentence");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the exercise is deleted");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Lesson");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to ApplicationUser");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PublisherId");

                    b.ToTable("TranslationExercises");
                });

            modelBuilder.Entity("LerningApp.Data.Models.UserCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to user");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Course");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Course completed at (UTC)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the UserCourse is deleted");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Course started at (UTC)");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UsersCourses");
                });

            modelBuilder.Entity("LerningApp.Data.Models.VocabularyCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK Unique Identifier");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Image of the VocabularyCard");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the VocabularyCard is deleted");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Lesson");

                    b.Property<Guid>("PartOfSpeechId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to PartOfSpeech");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PartOfSpeechId");

                    b.ToTable("VocabularyCards");
                });

            modelBuilder.Entity("LerningApp.Data.Models.VocabularyTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK Unique Identifier");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Example Sentence for the VocabularyTerm in German");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength()
                        .HasComment("German gender (der/die/das), only for Side = 'de'");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the VocabularyTerm is deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasComment("Is the VocabularyTerm primary for the VocabularyCard");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("The Side of the VocabularyTerm(en/de)");

                    b.Property<Guid>("VocabularyCardId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to VocabularyCard");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasComment("The Word of the VocabularyTerm");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyCardId", "Side");

                    b.ToTable("VocabularyTerms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LerningApp.Data.Models.Course", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Level", "Level")
                        .WithMany("CoursesForLevel")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.Teacher", "Publisher")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Lesson", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Course", "Course")
                        .WithMany("LessonsForCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LerningApp.Data.Models.Teacher", "Publisher")
                        .WithMany("CreatedLessons")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningExercise", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Lesson", "Lesson")
                        .WithMany("ListeningExercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.Teacher", "Publisher")
                        .WithMany("ListeningExercises")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningExerciseOption", b =>
                {
                    b.HasOne("LerningApp.Data.Models.ListeningQuestion", "ListeningQuestion")
                        .WithMany("Options")
                        .HasForeignKey("ListeningQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningQuestion");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningQuestion", b =>
                {
                    b.HasOne("LerningApp.Data.Models.ListeningExercise", "ListeningExercise")
                        .WithMany("Questions")
                        .HasForeignKey("ListeningExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.Teacher", "Publisher")
                        .WithMany("ListeningQuestions")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ListeningExercise");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LerningApp.Data.Models.MultipleChoiceExercise", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Lesson", "Lesson")
                        .WithMany("MultipleChoiceExercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.Teacher", "Publisher")
                        .WithMany("CreatedMultipleChoiceExercises")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Teacher", b =>
                {
                    b.HasOne("LerningApp.Data.Models.ApplicationUser", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("LerningApp.Data.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LerningApp.Data.Models.TranslationExercise", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Lesson", "Lesson")
                        .WithMany("TranslationExercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.Teacher", "Publisher")
                        .WithMany("CreatedTranslationExercises")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LerningApp.Data.Models.UserCourse", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Course", "Course")
                        .WithMany("CourseParticipants")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.ApplicationUser", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LerningApp.Data.Models.VocabularyCard", b =>
                {
                    b.HasOne("LerningApp.Data.Models.Lesson", "Lesson")
                        .WithMany("VocabularyCards")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.PartOfSpeech", "PartOfSpeech")
                        .WithMany("VocabularyCards")
                        .HasForeignKey("PartOfSpeechId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("PartOfSpeech");
                });

            modelBuilder.Entity("LerningApp.Data.Models.VocabularyTerm", b =>
                {
                    b.HasOne("LerningApp.Data.Models.VocabularyCard", "VocabularyCard")
                        .WithMany("Terms")
                        .HasForeignKey("VocabularyCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyCard");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LerningApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LerningApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LerningApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LerningApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LerningApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Teacher");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Course", b =>
                {
                    b.Navigation("CourseParticipants");

                    b.Navigation("LessonsForCourse");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Lesson", b =>
                {
                    b.Navigation("ListeningExercises");

                    b.Navigation("MultipleChoiceExercises");

                    b.Navigation("TranslationExercises");

                    b.Navigation("VocabularyCards");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Level", b =>
                {
                    b.Navigation("CoursesForLevel");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningExercise", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LerningApp.Data.Models.ListeningQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LerningApp.Data.Models.PartOfSpeech", b =>
                {
                    b.Navigation("VocabularyCards");
                });

            modelBuilder.Entity("LerningApp.Data.Models.Teacher", b =>
                {
                    b.Navigation("CreatedCourses");

                    b.Navigation("CreatedLessons");

                    b.Navigation("CreatedMultipleChoiceExercises");

                    b.Navigation("CreatedTranslationExercises");

                    b.Navigation("ListeningExercises");

                    b.Navigation("ListeningQuestions");
                });

            modelBuilder.Entity("LerningApp.Data.Models.VocabularyCard", b =>
                {
                    b.Navigation("Terms");
                });
#pragma warning restore 612, 618
        }
    }
}
